### ISSUE TITLE
Housing category doesn't work

### ISSUE THREAD

**Issue by kmay90** [newhere-team/nh-website#60] opened 2018-03-05 16:36 UTC
When you click on the sub-category 'Housing', nothing happens. Normally, even, if the category is empty, clicking on it displays the description.

**Comment by ScrambledRK** [comment] 2018-03-12 09:40
related to #51 (restructure categories) - the problem is although slugs (the name of a category in the url) is supposed to be unique, _housing_ exists twice. Once as a _parent_, once as a _child_ of that parent.

this is true for:
* housing
* emergency-accommodation
* repatriation-counselling
* training-opportunities

So what is happening is that when you browse to housing it chooses one over the other category disregarding the hierarchy. It could be fixed by respecting the hierarchy (`start > housing > housing` != `start > housing`) or we rename the categories. The latter is very easy and quick, especially since we have to rework the categories anyway (see #51)

**Closed as completed** 2018-03-20 10:25 UTC
Labels: bug
